language: go

go:
  - "1.14"

install:
  go get golang.org/x/tools/cmd/cover
  go get github.com/mattn/goveralls

secure: "QiYmqjNLYhGI1GUoxn9US9ODPVFjkSOFX4oQA2kqrBCbWL0bNaOhOpygB24UK5sWwTdECrfmHtE20nu+7kklnHJpHyz70LBmBK9TaFZDwYRQEEm/gIa52Jfh6LQeRqoj/7sqK3qb0GC8SjUrRjhfaePpKKIIzLZWY1Hyb80fanffyyIFEuzpG4fqHQOdSuVHawfXQrFsqyDNFaTfzsJt/33Ce52Wesl1A+zsghkP6oP+x8THgCEk/zL7xGXC22d22R5uKgXYjWGf2HjhWfMyYiejiROxfAl2npFULculvrFxl2uEj5IpvcvUM/uvleV2i2ep6DndlIGsgr18lvtFVFeKhegL+gmJ3cj5/X9r9zPH1cgk4gTcFSrQADOXzyIpLN6EcduyiQHriY9BHqeLF4bhD2PJSNwY/+I5y4KsR2J4iHfQK/b0CuYdFkkjxPn1wGERNRShSP1Df8vaIZKhOyEw9cxnXJjQBHFMyqrTEQ+QTaJCKIpDlArWCoodQeXgrP7IO93QvPnJRH8kxq56bpl1pi+l/mFZgUyYNNYeXv5zeKIzbcPU3+WYeIVmvEu5tpEE2doCEFa/JetieuTCDVmwRVpyjjJ4r6Lkrho7FAgQvEFh2DvJntroFLPuWqODVHnFYDCadEgGuzqzO4uoLFfLitImvxUdsGUS6usW+e8="

script:  
  go test -v -covermode=count -coverprofile=coverage.out
  $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken  $COVERALL_TOKEN
#addons:
#    sonarcloud:
#        organization: "phutson" # the key of the org you chose at step #3
#        token:
#            secure: "KP8ws+sgbomxqqvJCn+mmMyzDhxA7Jo6yIRvXhUz7a85xNtM3oW0AnT9HXjXk68VKAX8euBFJZsiwl38Z8DZE7vln95lA4eX88ZxTx3pYNJaXOwHNKloLlxGu+3aro3/mJsuV4P0dCT422FTIULfBXUsqvDhIGAAh1ZEdYZQStTmGl0tODjDHmEQ8W+qY8Ypx6rRPbWu1V3P6jqGurX0DNXLxr6V9zr0wgt5psE/tveS7d/85fErGAjCSTIl9cEUVgxBtTvBvwjhrThkCHyCsR0F+uBXsjY40wjc1UkoZZ1iidOWJWfJVUE0IpoeBRoMwFmX0xq8AVX+scT+c+TgbqzFwOYg+bK4yOGR4QzX8QETC9SjXdFDkt+mt4VL9U9sGJar8vMLqZVx30IYSNlQl2DespROaB9di2c+vsyZCFyLju0/Nf8CHGWrcjsjzxs2w5uCGaEvEwFzMVaMnMDYOKBkPnJhKfq2qNoVaFIeAml/p/2id5B52dy6ZaMxoyC63Ky2s20ZLcSuiG4c5krUPG9LsJvtB4lObT7np1JBEfRPYWUvqspsI/eL9nGOZIa5jFUiAN648dubPmoA1Z+PsaNpKhOgZ0c5M6lpDqb8f1HevQ673BBPN+kQJmploYEF2AhezYtj+NfTZ5krkXpu0ift9tux6Au412yfg9LgnKk="
#script:
    # other script steps might be done before running the actual analysis
#    - sonar-scanner